//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int id_Ticket { get; set; }
        public string persona_Sol { get; set; }
        public string asunto { get; set; }
        public string descrip_incidencia { get; set; }
        public System.DateTime fecha_Ingreso { get; set; }
    }
}
